#pragma once

#include "NativeGameplayTags.h"

namespace GtGameplayTags
{
	/** Attribute Primary Tags */
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Health);

	/** Input Tags */
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PrimaryAction);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SecondaryAction);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload);

	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipSlot1);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipSlot2);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseGrenade);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseConsumable);
	
	/** Status Tags */
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Action);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Action_WallRunning);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Action_WallRunning_Left);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Action_WallRunning_Right);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Action_Crouching);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Action_Sliding);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Action_Sprinting);
	GIGANTES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dead);
}